# Use official Node.js image
FROM node:16

# Set the working directory
WORKDIR /app

# Install dependencies
COPY arba_travel_frontend/package.json arba_travel_frontend/package-lock.json /app/
RUN npm install

# Copy the rest of the application code
COPY . /app/

# Expose the React app on port 3000
EXPOSE 3000

# Run the React app
CMD ["npm", "start"]
